language: node_js
node_js:
  - 8.11.2
script:
  - npm test
  - npm run storybook
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
